name: Production Publish

on:
  release:
    types: [published]

env:
  version: ${{ github.ref_name }}
  build_folder: './build'
  s3_bucket: 'access8math-web'
  environment: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with github package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Bump npm version
        run: npm version ${{ env.version }} --no-git-tag-version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Generate version.txt
        run: echo "$version" > "${build_folder}/version.txt"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
          aws-region: ap-northeast-1

      - name: upload build folder
        run: |
          aws s3 sync "$build_folder" "s3://${s3_bucket}/${environment}/${version}/"
