name: Production Publish

on:
  release:
    types: [published]

env:
  version: ${{ github.ref_name }}
  build_folder: './build'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install dependencies
      #   run: npm install
      #
      # - name: Build project
      #   run: npm run build

      - name: Generate version.txt
        run: echo "$version" > "${build_folder}/version.txt"

      - name: list
        run: ls -al $build_folder

      - name: cat the version.txt
        run: cat "${build_folder}/version.txt"

      # - name: Upload to S3
      #   uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete
      #   env:
      #     AWS_S3_BUCKET: <YOUR_S3_BUCKET>
      #     AWS_REGION: <YOUR_AWS_REGION>
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
